name = "Harmony"
author = "lia.lopes"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fa60a0fcc06ea72c58061341e3e863b63bdf1084075a9ee610ec5c323443e25"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
