name = "Harmony"
author = "lia.lopes"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1006482bdef0bd18b7fdc0630099abcfd26e3a681b95f8b19517617fe1a84a7a"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
