name = "Harmony"
author = "lia.lopes"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd97b68e48f2027ea4460c856d1a11a40184ef5bd5dc1b7ae4a9fcb8d8cc24a"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
